Fusion_HM/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

hostel_management/urls.py
from django.conf.urls import url

app_name = 'hostelmanagement'

urlpatterns = [
    url('allotedroom', views.alloted_room, name="allotedroom"),
    url('upload', views.add_hall_room, name="upload"),
]

hostel_management/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User
from applications.globals.models import ExtraInfo, Staff
from applications.academic_information.models import Student
from applications.complaint_system.models import Caretaker
from django.utils import timezone

class HostelManagementConstants:
    ROOM_STATUS = (
        ('Booked', 'Booked'),
        ('CheckedIn', 'CheckedIn'),
        ('Available', 'Available'),
        ('UnderMaintenance', 'UnderMaintenance'),
        )

    DAYS_OF_WEEK = (
            (0, 'Monday'),
            (1, 'Tuesday'),
            (2, 'Wednesday'),
            (3, 'Thursday'),
            (4, 'Friday'),
            (5, 'Saturday'),
            (6, 'Sunday')
        )
    BOOKING_STATUS = (
        ("Confirmed" , 'Confirmed'),
        ("Pending" , 'Pending'),
        ("Rejected" , 'Rejected'),
        ("Canceled" , 'Canceled'),
        ("CancelRequested" , 'CancelRequested'),
        ("CheckedIn" , 'CheckedIn'),
        ("Complete", 'Complete'),
        ("Forward", 'Forward')
    )


class GuestRoomDetail(models.Model):
    room_no = models.CharField(max_length=4, unique=True)
    hall_no = models.IntegerField(default=1)
    room_status  = models.CharField(max_length=20, choices=HostelManagementConstants.ROOM_STATUS, default='Available')

    def _str_(self):
        return self.room_no


class GuestDetails(models.Model):
    guest_phone = models.CharField(max_length=15)
    guest_name = models.CharField(max_length=40)
    guest_email = models.CharField(max_length=40, blank=True)
    guest_address = models.TextField(blank=True)
    nationality = models.CharField(max_length=20, blank=True)

    def _str_(self):
        return '{} - {}'.format(self.id, self.guest_name)


class GuestRoomBooking(models.Model):
    caretaker_id = models.ForeignKey(Caretaker, on_delete=models.CASCADE)
    student_id = models.ForeignKey(Student, on_delete=models.CASCADE)
    guest_id = models.ForeignKey(GuestDetails, on_delete=models.CASCADE)
    room_id = models.ManyToManyField(GuestRoomDetail)
    # number_of_rooms =  models.IntegerField(default=1,null=True,blank=True)
    total_guest = models.IntegerField(default=1)
    relation_with_student = models.CharField(max_length=50)
    purpose = models.TextField(default="Hi!")
    booking_from = models.DateField()
    booking_upto = models.DateField()
    #total_days = models.IntegerField(default=1)
    status = models.CharField(max_length=15, choices=HostelManagementConstants.BOOKING_STATUS ,default ="Pending")
    booking_date = models.DateField(auto_now_add=False, auto_now=False, default=timezone.now)
    
    def _str_(self):
        return '%s ----> %s - %s' % (self.id, self.guest_id, self.status)


class StaffSchedule(models.Model):
    staff_id = models.ForeignKey(Staff, on_delete=models.ForeignKey)
    day = models.IntegerField(choices=HostelManagementConstants.DAYS_OF_WEEK)
    start_time = models.TimeField(null=True,blank=True)
    end_time = models.TimeField(null=True,blank=True)
    #date = models.DateField(auto_now=True)

    def _str_(self):
        return str(self.staff_id) + str(self.start_time) + '->' + str(self.end_time)
    

class HostelNoticeBoard(models.Model):
    user = models.ForeignKey(User, on_delete=models.ForeignKey)
    hall_no = models.IntegerField(default=1)
    head_line = models.CharField(max_length=100)
    content = models.FileField(upload_to='hostel_management/', blank=True, null=True)
    description = models.TextField(blank=True)

    def _str_(self):
        return self.head_line

class HostelStudentAttendence(models.Model):
    student_id = models.ForeignKey(Student, on_delete=models.CASCADE)
    date = models.DateField()
    present = models.BooleanField()
    
    def _str_(self):
        return str(self.student_id) + '->' + str(self.date) + '-' + str(self.present)

hostel_management/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from applications.globals.models import (Designation, ExtraInfo,
                                         HoldsDesignation, DepartmentInfo)
from applications.academic_information.models import *

# Create your views here.

@login_required
def view_alloted_room(request):
    hall_1_student = Student.objects.filter(hall_no=1)
    hall_3_student = Student.objects.filter(hall_no=3)
    hall_4_student = Student.objects.filter(hall_no=4)[:10]                        

    context = {
        'hall_1_student': hall_1_student,
        'hall_3_student': hall_3_student,
        'hall_4_student': hall_4_student
    }

    return render(request, 'hostelmanagement/hostel.html', context)


    def add_hall_room(request):
    if request.method == "GET":
        files = request.FILES['hallroom']
        excel = pd.read_csv(files)
        roll_no = excel['ROLL NO.']
        hall_no = excel['Hall']
        room_no = excel['ROOM NO']
        for roll, hall, room in zip(roll_no,hall_no,room_no):
            student = Student.objects.get(id__id=roll)
            student.hall_no = hall
            student.room_no = room
            print("success GM==")
    return render(request, 'hostelmanagement/hall_upload.html')

templates/add_student.html
{% block add_student %}
<h3 align="center"> Student Room Allotment Application Form </h3><br><br>
<!-- <form action="{%url 'office_module:teaching_form' %}" method ="POST"> -->
<form action="#" method ="POST">
   {% comment %}The add a new skill Accordian starts here!{% endcomment %}
   <div class="ui form" style="padding: 8px; padding-left: 24px; padding-right: 24px;">
        {% csrf_token %}
        
       <div class="three fields">
           <div class="six wide field">
               <label>Roll no.</label>
               <input value="" class="ui large input" name="roll_no" required onkeypress="return isNumberKey(event)">
           </div>

           <div class="six wide field">
               <label>Name</label>
               <input value="" class="ui large input" name="name" required>
           </div>

           <div class="six wide field">
                <label>Room no.</label>
                <input value="" class="ui large input" name="room_no" required>
           </div>
           
       </div>
       
       <div class="two fields">
           <div class="six wide field">
               <label>Programme</label>
               <select class="ui search fluid dropdown" name="programme" required>
                   <option value="">Select</option>
                   <option value="Phd">Phd</option>
                   <option value="BTech">BTech</option>
                   <option value="Design">Design</option>
               </select>
           </div>

           <div class="six wide field">
               <label>Branch</label>
               <select class="ui search fluid dropdown" name="branch" required>
                   <option value="">Select</option>
                   <option value="CSE">CSE</option>
                   <option value="ME">ME</option>
                   <option value="ECE">ECE</option>
               </select>
           </div>
           
       </div>
       
       <!-- <div class="three fields">
           <div class="six wide field">
               <label>Course 1</label>
               <select class="ui search fluid dropdown" name="course1" required>
                   <option value="">Select</option>
                   <option value="Computer Graphics">Computer Graphics</option>
                   <option value="Machine Learning">Machine Learning</option>
                   <option value="Image Processing">Image Processing</option>
                   <option value="Data Structure">Data Structure</option>
               </select>
           </div>

           <div class="six wide field">
               <label>Course 2</label>
               <select class="ui search fluid dropdown" name="course2" required>
                   <option value="">Select</option>
                   <option value="Computer Graphics">Computer Graphics</option>
                   <option value="Machine Learning">Machine Learning</option>
                   <option value="Image Processing">Image Processing</option>
                   <option value="Data Structure">Data Structure</option>
               </select>
           </div>

           <div class="six wide field">
               <label>Course 3</label>
               <select class="ui search fluid dropdown" name="course3" required>
                   <option value="">Select</option>
                   <option value="Computer Graphics">Computer Graphics</option>
                   <option value="Machine Learning">Machine Learning</option>
                   <option value="Image Processing">Image Processing</option>
                   <option value="Data Structure">Data Structure</option>
               </select>
           </div>
       </div> -->

       <div class="field">
           <button class="ui primary button right floated" type="submit">
               Submit
           </button>
       </div>
   </div>
</form>

<br>
<br>
<div class="ui divider"></div>
<script type="text/javascript">
   
   function isNumberKey(evt){
   var charCode = (evt.which) ? evt.which : event.keyCode
   if (charCode > 31 && (charCode < 48 || charCode > 57))
       return false;
   return true;
}

</script>

 {% endblock %}

templates/allotted_hostel_room.html
{% block allotted_hostel_room %}
<div class="ui pointing secondary menu">
  <a class="item active" data-tab="hall1">
    Hall 1
  </a>
  <a class="item" data-tab="hall3">
    Hall 3
  </a>
  <a class="item" data-tab="hall4">
    Hall 4
  </a>
  <a class="item" data-tab="add_student">
    Add Student
  </a>
  <a class="item" data-tab="hall_upload">
    Upload File
  </a>
</div>


<div class="ui active tab" data-tab="hall1" >
    <div class="textLoader" style="max-height: 64vh; overflow-y: auto; overflow-x: hidden;">
        {% block hall1 %}
            {% include 'hostelmanagement/hall1.html' %}
        {% endblock %}
    </div>
</div>


<div class="ui tab" data-tab="hall3">
    <div class="textLoader" style="max-height: 64vh; overflow-y: auto; overflow-x: hidden;">
        {% block hall3 %}
            {% include 'hostelmanagement/hall3.html' %}
        {% endblock %}
    </div>
</div>


<div class="ui tab" data-tab="hall4">
    <div class="textLoader" style="max-height: 64vh; overflow-y: auto; overflow-x: hidden;">
            {% block hall4 %}
                {% include 'hostelmanagement/hall4.html' %}
            {% endblock %}
        
    </div>
</div>


<div class="ui tab" data-tab="add_student">
    <div class="ui vertical segment">
        {% block add_student %}
            {% include 'hostelmanagement/add_student.html' %}
        {% endblock %}
    </div>
</div>

<div class="ui tab" data-tab="hall_upload">
    <div class="ui vertical segment">
        {% block hall_upload %}
            {% include 'hostelmanagement/hall_upload.html' %}
        {% endblock %}
    </div>
</div>

{% comment %} <div class="ui active tab" data-tab="hall1">
        <div class="ui vertical segment">
            <table class="ui very basic collapsing celled sortable table"
       style="padding-left: 5%;
            padding-right: 5%;
            padding-top: 1%;
            padding-bottom: 1.5%;
            margin: auto;">
    <thead>
    <tr>

        <th class="one wide column">
            Roll No
        </th>

        <th class="six wide column">
            Name
        </th>

        <th class="four wide column">
            Program
        </th>

        <th class="four wide column">
            Room No
        </th>

    </tr>
    </thead>

    <tbody>
    <tr>
        <td>
            {{hall_1_student.id}}
        </td>

        <td>
            {{hall_1_student.id.user.username}}
        </td>

        <td>
            {{hall_1_student.programme}}
        </td>

        <td>
            {{hall_1_student.room_no}}
        </td>

    </tr>

    </tbody>
</table>
        </div>
    </div>

<div class="ui active tab" data-tab="hall1">
        <div class="ui vertical segment">
            <table class="ui very basic collapsing celled sortable table"
       style="padding-left: 5%;
            padding-right: 5%;
            padding-top: 1%;
            padding-bottom: 1.5%;
            margin: auto;">
    <thead>
    <tr>

        <th class="one wide column">
            Roll No
        </th>

        <th class="six wide column">
            Name
        </th>

        <th class="four wide column">
            Program
        </th>

        <th class="four wide column">
            Room No
        </th>

    </tr>
    </thead>

    <tbody>
    <tr>
        <td>
            {{hall_3_student.id}}
        </td>

        <td>
            {{hall_3_student.id.user.username}}
        </td>

        <td>
            {{hall_3_student.programme}}
        </td>

        <td>
            {{hall_3_student.room_no}}
        </td>

    </tr>

    </tbody>
</table>
        </div>
    </div>

<div class="ui active tab" data-tab="hall1">
        <div class="ui vertical segment">
            <table class="ui very basic collapsing celled sortable table"
       style="padding-left: 5%;
            padding-right: 5%;
            padding-top: 1%;
            padding-bottom: 1.5%;
            margin: auto;">
    <thead>
    <tr>

        <th class="one wide column">
            Roll No
        </th>

        <th class="six wide column">
            Name
        </th>

        <th class="four wide column">
            Program
        </th>

        <th class="four wide column">
            Room No
        </th>

    </tr>
    </thead>

    <tbody>
    <tr>
        <td>
            {{hall_4_student.id}}
        </td>

        <td>
            {{hall_4_student.id.user.username}}
        </td>

        <td>
            {{hall_4_student.programme}}
        </td>

        <td>
            {{hall_4_student.room_no}}
        </td>

    </tr>

    </tbody>
</table>
        </div>
    </div> {% endcomment %}

<br>
<br>

<div class="ui divider"></div>

{% endblock %}

templates/hall1.html
{% block hall1 %}
 <table class="ui very basic collapsing celled sortable table"
       style="padding-left: 5%;
            padding-right: 5%;
            padding-top: 1%;
            padding-bottom: 1.5%;
            margin: auto;">
    <thead>
    <tr>

        <th class="one wide column">
            Roll No
        </th>

        <th class="six wide column">
            Name
        </th>

        <th class="four wide column">
            Program
        </th>

        <th class="four wide column">
            Room No
        </th>

    </tr>
    </thead>

    <tbody>
    {% for student in hall_1_student %}
    <tr>
    
        <td>
            {{student.id.id}}
        </td>

        <td>
            {{student.id.user.username}}
        </td>

        <td>
            {{student.programme}}
        </td>

        <td>
            {{student.room_no}}
        </td>

    </tr>
     {% endfor %} 

    </tbody>
</table>
{% endblock %}

templates/hall3.html
{% block hall3 %}
 <table class="ui very basic collapsing celled sortable table"
       style="padding-left: 5%;
            padding-right: 5%;
            padding-top: 1%;
            padding-bottom: 1.5%;
            margin: auto;">
    <thead>
    <tr>

        <th class="one wide column">
            Roll No
        </th>

        <th class="six wide column">
            Name
        </th>

        <th class="four wide column">
            Program
        </th>

        <th class="four wide column">
            Room No
        </th>

    </tr>
    </thead>

    <tbody>
    {% for student in hall_3_student %}
    <tr>
        <td>
            {{student.id}}
        </td>

        <td>
            {{student.id.user.username}}
        </td>

        <td>
            {{student.programme}}
        </td>

        <td>
            {{student.room_no}}
        </td>

    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/hall4.html
{% block hall4 %}
 <table class="ui very basic collapsing celled sortable table"
       style="padding-left: 5%;
            padding-right: 5%;
            padding-top: 1%;
            padding-bottom: 1.5%;
            margin: auto;">
    <thead>
    <tr>

        <th class="one wide column">
            Roll No
        </th>

        <th class="six wide column">
            Name
        </th>

        <th class="four wide column">
            Program
        </th>

        <th class="four wide column">
            Room No
        </th>

    </tr>
    </thead>

    <tbody>
    {% for student in hall_4_student %}
    <tr>
    
         <td>
            {{student.id.id}}
        </td>

        <td>
            {{student.id.user.first_name}} {{' '}} {{student.id.user.last_name}}
        </td>

        <td>
            {{student.programme}}
        </td>

        <td>
            {{student.room_no}}
        </td> 

         {% comment %} <td>
            fgf
        </td>

        <td>
            fdgdg
        </td>

        <td>
            htfh
        </td>

        <td>
           ytry
        </td> {% endcomment %}

    </tr>
    {% endfor %}

    </tbody>
</table>
{% endblock %}

templates/hall_upload.html
{% block hall_upload %}
<h3 align="center"> Student Room Allotment Application Form </h3><br><br>
<!-- <form action="{%url 'office_module:teaching_form' %}" method ="POST"> -->
<form action="{% url 'hostelmanagement:upload' %}" method ="POST" >
   {% comment %}The add a new skill Accordian starts here!{% endcomment %}
   <div class="ui form" style="padding: 8px; padding-left: 24px; padding-right: 24px;">
        {% csrf_token %}
        
       <div class="field">
           <input type='file' name='hallroom' > 

           <button class="ui primary button right floated" type="submit">
               Submit
           </button>
       </div>
   </div>
</form>

<br>
<br>
<div class="ui divider"></div>
<script type="text/javascript">
   
   function isNumberKey(evt){
   var charCode = (evt.which) ? evt.which : event.keyCode
   if (charCode > 31 && (charCode < 48 || charCode > 57))
       return false;
   return true;
}

</script>

 {% endblock %}

templates/hostel.html
{% extends 'globals/base.html' %}
{% load static %}

{% block title %}
    Hostel
{% endblock %}


{% block body %}
    {% block navBar %}
        {% include 'dashboard/navbar.html' %}
    {% endblock %}


    {% comment %}The grid starts here!{% endcomment %}
    <div class="ui stackable doubling grid">

        {% comment %}The left-margin segment!{% endcomment %}
        <div class="column"></div>

        {% comment %}The left-rail segment starts here!{% endcomment %}
        <div class="three wide column">

            {% comment %}ROW #1 starts here!{% endcomment %}
            <div class="row">
                {% comment %}The Employee Image Card starts here!{% endcomment %}
                {% block userCard %}
                    {% include 'globals/usercard.html' %}
                {% endblock %}
                {% comment %}The Employee Image Card ends here!{% endcomment %}
            </div>
            {% comment %}ROW #1 ends here!{% endcomment %}

            <div class="ui divider"></div>

            {% comment %}ROW #2 starts here!{% endcomment %}
            <div class="row">
                {% comment %}The Tab-Menu starts here!{% endcomment %}
                <div class="ui large fluid vertical pointing menu">
                    <a class="active item" data-tab="first">
                        View Alloted Room
                        <i class="right floated chevron right icon"></i>
                    </a>
                {% comment %}The Tab-Menu ends here!{% endcomment %}


                {% comment %}The Tab-Menu starts here!{% endcomment %}
                    <a class="item" data-tab="second">
                        Staff's Schedule
                        <i class="right floated chevron right icon"></i>
                    </a>
                {% comment %}The Tab-Menu ends here!{% endcomment %}


                {% comment %}The Tab-Menu starts here!{% endcomment %}
                    <a class="item" data-tab="third">
                        Book Guest Room 
                        <i class="right floated chevron right icon"></i>
                    </a>

                </div>
                {% comment %}The Tab-Menu ends here!{% endcomment %}

            </div>
            {% comment %}ROW #2 ends here!{% endcomment %}

        </div>

        {% comment %}The left-rail segment ends here!{% endcomment %}

        {% comment %}The central-rail segment starts here!{% endcomment %}
        <div class="eight wide column">
            {% comment %}The View Alloted Room Form starts here!{% endcomment %}
            <div class="ui active tab segment" data-tab="first">
                {% block allotted_hostel_room %}
                    {% include 'hostelmanagement/allotted_hostel_room.html'%}
                {% endblock %}
            </div>
            {% comment %}The View Alloted Room Form ends here!{% endcomment %}

        </div>
        {% comment %}The central-rail segment ends here!{% endcomment %}


    </div>



{% endblock %}